env:
  region:             "us-central1"
  app_name:           "artemis"
  app_version:        ${GITHUB_SHA}
  app_port:           "5000"
  cluster_name:       "project-cluster"
  helm_repository:    "https://github.com/sanyoc/artemis-helm-chart"
  environment:        "prod"


name: ContinuousDeployment

# Controls when the workflow will run
on:
  # Triggers the workflow only when workflow "ContinuousDelivery" is completed successuful 
  workflow_run:
    workflows: ["ContinuousIntegration"]
    types:
      - completed
  
  # Allows you to run this workflow manually from the Actions tab     
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # Clone Helm Chart Repository
      - name: Clone Helm Chart Repository
        run: |
          git clone "${{ env.helm_repository }}"
          
      # Creates an environment variable    
      - name: Set the value for work_dir variable
        run: echo "work_dir=$(echo ${{ env.helm_repository }} | awk -F '/' '{ print $NF }')" >> $GITHUB_ENV
      
      # Import Secret from Vault
      - name: Import Secret from Vault
        uses: hashicorp/vault-action@v2
        with:
          url: ${{ secrets.VAULT_URL }}
          token: ${{ secrets.VAULT_TOKEN }}
          secrets: |
            artemis/data/gh_actions project_id ;
            artemis/data/gh_actions service_account ;
            artemis/data/gh_actions domain_name
      
      # Authenticate to Google Cloud Platform 
      - id: 'auth'
        name: 'Authenticate to Google Cloud Platform'
        uses: 'google-github-actions/auth@v0.4.0'
        with:
          credentials_json: '${{ env.SERVICE_ACCOUNT }}'
        
      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: 'project-cluster'
          location: 'us-central1'

      # The KUBECONFIG env var is automatically exported and picked up by kubectl.
      - id: 'kubeconfig'
        run: 'mkdir ~/.kube && cat $KUBECONFIG > ~/.kube/config'

      # Configure Backend and Initialize
      - name: Configure Backend
        working-directory: "${{ env.work_dir }}"
        run: |
          bash setenv.sh  
      
      # Deploy the Application
      - name: Deploy the Application
        working-directory: "${{ env.work_dir }}"
        env:
          repository: "us-central1-docker.pkg.dev/${{ env.PROJECT_ID }}/artemis/artemis"
        run: |
          terraform apply   \
          -var app_name="${{ env.app_name }}"   \
          -var app_version="${{ env.app_version }}"   \
          -var app_port="${{ env.app_port }}"   \
          -var google_domain_name="${{ env.DOMAIN_NAME }}"   \
          -var region="${{ env.region }}"   \
          -var project_id="${{ env.PROJECT_ID }}"   \
          -var environment="${{ env.environment }}"   \
          -var repository="${{ env.repository }}"   \
          -var email_list=${{ vars.EMAIL }}   \
          --auto-approve
          
#         vars.EMAIL must be this format: '["email1@gmail.com", "email2@gmail.com"]'
      
